"""empty message

Revision ID: 510d33716dd5
Revises: 8f53854e2699
Create Date: 2022-03-05 21:10:44.800259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510d33716dd5'
down_revision = '8f53854e2699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_answer_dislike',
    sa.Column('answers_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answers_id'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('user_answers',
    sa.Column('answers_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answers_id'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_answers')
    op.drop_table('user_answer_dislike')
    # ### end Alembic commands ###
